apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "axon.labels" . | nindent 4 }}
stringData:
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.config.REDIS_URL | quote }}
  API_KEY: {{ .Values.config.API_KEY | quote }}
