/**
 * DemoBanner — persistent disclosure banner shown on every dashboard page.
 *
 * Makes explicit that the data behind these charts is real output from
 * running Traject's compression engine against the public SWE-Gym
 * benchmark trajectories (see backend/scripts/seed_demo_data.py), not
 * live production traffic.
 */

import { Info } from "lucide-react";

export default function DemoBanner(): JSX.Element {
  return (
    <div className="flex items-center gap-2 bg-teal-950/40 border-b border-teal-800/50 px-6 py-2 text-xs text-teal-300">
      <Info className="h-3.5 w-3.5 flex-shrink-0" aria-hidden="true" />
      <span>
        Sample data from the public SWE-Gym benchmark trajectories, generated by
        running Traject&apos;s real compression engine on real agent transcripts
        &mdash; not live production traffic.
      </span>
    </div>
  );
}
